# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-13 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('linkTo', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
